// Generated by CoffeeScript 1.9.0
var f, g, sum,
  __slice = [].slice;

f = function() {
  return "bar";
};

g = function(a, b) {
  return a * b;
};

sum = function() {
  var nums, result;
  nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  result = 0;
  return nums.forEach(function(n) {
    return result += n;
  });
};

this.clickHandler = function() {
  return alert("clicked");
};

element.addEventListener("click", (function(_this) {
  return function(e) {
    return _this.clickHandler(e);
  };
})(this));
